In [1]:
import pandas as pd
print("Pandas funciona correctamente")

Pandas funciona correctamente

In [2]:
car_data =pd.read_csv('../vehicles_us.csv')

In [3]:
car_data.head()

,price,model_year,model,condition,cylinders,fuel,odometer,transmission,type,paint_color,is_4wd,date_posted,days_listed
0,9400,2011.0,bmw x5,good,6.0,gas,145000.0,automatic,SUV,NaN,1.0,2018-06-23,19
1,25500,NaN,ford f-150,good,6.0,gas,88705.0,automatic,pickup,white,1.0,2018-10-19,50
2,5500,2013.0,hyundai sonata,like new,4.0,gas,110000.0,automatic,sedan,red,NaN,2019-02-07,79
3,1500,2003.0,ford f-150,fair,8.0,gas,NaN,automatic,pickup,NaN,NaN,2019-03-22,9
4,14900,2017.0,chrysler 200,excellent,4.0,gas,80903.0,automatic,sedan,black,NaN,2019-04-02,28

In [4]:
car_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 51525 entries, 0 to 51524
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   price         51525 non-null  int64
 1   model_year    47906 non-null  float64
 2   model         51525 non-null  str
 3   condition     51525 non-null  str
 4   cylinders     46265 non-null  float64
 5   fuel          51525 non-null  str
 6   odometer      43633 non-null  float64
 7   transmission  51525 non-null  str
 8   type          51525 non-null  str
 9   paint_color   42258 non-null  str
 10  is_4wd        25572 non-null  float64
 11  date_posted   51525 non-null  str
 12  days_listed   51525 non-null  int64
dtypes: float64(4), int64(2), str(7)
memory usage: 7.7 MB

In [5]:
car_data.isna().sum()

price               0
model_year       3619
model               0
condition           0
cylinders        5260
fuel                0
odometer         7892
transmission        0
type                0
paint_color      9267
is_4wd          25953
date_posted         0
days_listed         0
dtype: int64

In [6]:
car_data.describe()

,price,model_year,cylinders,odometer,is_4wd,days_listed
count,51525.000000,47906.000000,46265.000000,43633.000000,25572.0,51525.00000
mean,12132.464920,2009.750470,6.125235,115553.461738,1.0,39.55476
std,10040.803015,6.282065,1.660360,65094.611341,0.0,28.20427
min,1.000000,1908.000000,3.000000,0.000000,1.0,0.00000
25%,5000.000000,2006.000000,4.000000,70000.000000,1.0,19.00000
50%,9000.000000,2011.000000,6.000000,113000.000000,1.0,33.00000
75%,16839.000000,2014.000000,8.000000,155000.000000,1.0,53.00000
max,375000.000000,2019.000000,12.000000,990000.000000,1.0,271.00000

In [7]:
car_data['condition'].value_counts()

condition
excellent    24773
good         20145
like new      4742
fair          1607
new            143
salvage        115
Name: count, dtype: int64

In [16]:
car_data['model'].value_counts().head(15)

model
ford f-150                    2796
chevrolet silverado 1500      2171
ram 1500                      1750
chevrolet silverado           1271
jeep wrangler                 1119
ram 2500                      1091
toyota camry                   990
honda accord                   964
chevrolet silverado 2500hd     915
gmc sierra 1500                906
ford explorer                  847
ford escape                    841
toyota tacoma                  827
honda civic                    815
nissan altima                  813
Name: count, dtype: int64

In [17]:
car_data['type'].value_counts()

type
SUV            12405
truck          12353
sedan          12154
pickup          6988
coupe           2303
wagon           1541
mini-van        1161
hatchback       1047
van              633
convertible      446
other            256
offroad          214
bus               24
Name: count, dtype: int64

In [18]:
car_data.duplicated().sum()

np.int64(0)

In [20]:
car_data[car_data['price']<1000]['price'].value_counts().sort_index()

price
1      798
3        1
5        1
6        1
9        1
      ...
900     18
950     16
975      4
995     17
999     14
Name: count, Length: 116, dtype: int64

In [21]:
(car_data['price']<1000).mean() *100

np.float64(2.7248908296943233)

In [30]:
import nbformat
print(nbformat.__version__)
print(nbformat.__file__)

5.11.0
c:\Users\avill\Desktop\TripleTen\s6\Sprint-6\.venv\Lib\site-packages\nbformat\__init__.py

In [31]:
import plotly.io as pio
pio.renderers.default = 'vscode'

In [28]:
import plotly.express as px

In [33]:
import plotly.io as pio
print(pio.renderers.default)
print(pio.renderers)

vscode
Renderers configuration
-----------------------
    Default renderer: 'vscode'
    Available renderers:
        ['plotly_mimetype', 'jupyterlab', 'nteract', 'vscode',
         'notebook', 'notebook_connected', 'kaggle', 'azure', 'colab',
         'cocalc', 'databricks', 'json', 'png', 'jpeg', 'jpg', 'svg',
         'pdf', 'browser', 'firefox', 'chrome', 'chromium', 'iframe',
         'iframe_connected', 'sphinx_gallery', 'sphinx_gallery_png']

In [34]:
fig = px.histogram(car_data, x='price')
print(type(fig))

<class 'plotly.graph_objs._figure.Figure'>

In [36]:
fig = px.scatter(car_data, x='odometer', y='price')
print(type(fig))

<class 'plotly.graph_objs._figure.Figure'>

In [37]:
car_data[['odometer','price']].corr()

          odometer     price
odometer  1.000000 -0.420299
price    -0.420299  1.000000